name: R Package Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.3'
        
    - name: Check R package
      run: R CMD check .
      
    - name: Build R package
      run: R CMD build .
