name: R Package Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install R
        run: |
          sudo apt-get update -y
          sudo apt-get install -y r-base

      - name: Install system dependencies
        run: |
          sudo apt-get install -y qpdf pkg-config
          sudo apt-get install -y qpdf pkg-config texlive-latex-base
        
      - name: Check R package
        run: cd $GITHUB_WORKSPACE && R CMD check ./DESCRIPTION

      - name: Build R package
        working-directory: ${{ github.workspace }}
        run: R CMD build .
