name: R Package Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.x'

      - name: Install system dependencies
        run: |
          sudo apt-get install -y qpdf pkg-config
          sudo apt-get install -y qpdf pkg-config texlive-latex-base

      - name: Check R package
        working-directory: ${{ github.workspace }}
        run: R CMD check .

      - name: Build R package
        working-directory: ${{ github.workspace }}
        run: R CMD build .
