name: R Package Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.x'

      - name: Install system dependencies
        run: |
          sudo apt-get install -y qpdf pkg-config

      - name: Install LaTeX
        run: |
          sudo apt-get install -y texlive-latex-base

      - name: Check R package
        run: cd $GITHUB_WORKSPACE && R CMD check ./DESCRIPTION

      - name: Build R package
        run: |
          cd $GITHUB_WORKSPACE
          R CMD build .
