name: R Package Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install R
        run: |
          sudo apt-get update -y
          sudo apt-get install -y r-base

      - name: Install system dependencies
        run: |
          sudo apt-get install -y qpdf pkg-config

      - name: Install LaTeX
        run: |
          sudo apt-get install -y texlive-latex-base

             
      - name: Install R dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)

      - name: Check R package
        run: |
          R CMD build .
          PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
          R CMD check "${PKG_FILE_NAME}"

      - name: Build R package
        run: R CMD build .



