name: R Package Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install R
        run: |
          sudo apt-get update -y
          sudo apt-get install -y r-base

      - name: Install system dependencies
        run: |
          sudo apt-get install -y qpdf pkg-config

      - name: Install LaTeX
        run: |
          sudo apt-get install -y texlive-latex-base

             
      - name: Install devtools
        run: |
          Rscript -e "install.packages('devtools', repos = 'http://cran.rstudio.com/')"

      - name: Build R package
        run: |
          cd $GITHUB_WORKSPACE
          Rscript -e "devtools::build()"

      - name: Check R package
        run: cd $GITHUB_WORKSPACE && R CMD check ./DESCRIPTION.



